AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
